# Generated by Django 5.1.1 on 2024-09-05 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_selling_system', '0002_alter_sessioninfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioninfo',
            name='time_of_session',
        ),
        migrations.AddField(
            model_name='sessioninfo',
            name='datetime_of_session',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 14, 3, 0, 179384), verbose_name='Время сеанса'),
            preserve_default=False,
        ),
    ]
