# Generated by Django 5.1.1 on 2024-09-05 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_selling_system', '0003_remove_sessioninfo_time_of_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='session_datetime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket_selling_system.sessioninfo'),
            preserve_default=False,
        ),
    ]
