# Generated by Django 5.1.1 on 2024-09-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_selling_system', '0004_ticket_session_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='session_datetime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_selling_system.sessioninfo', verbose_name='Выбранный сеанс'),
        ),
    ]
